from .ge_exception import GeException

class GeDuplicateApplianceError(GeException):
    """Error raised when a duplicate appliance is attempted to be added"""
    pass
